name: Cypress Tests

on: 
    push:
    workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
        fail-fast: false
        matrix:
            browsers: [chrome, firefox, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run in ${{ matrix.browsers }}
        uses: cypress-io/github-action@v6
        with:
            browsers: ${{ matrix.browsers }}
            command: npx cypress run --browser ${{ matrix.browsers }} --reporter-options reportDir=cypress/reports/${{ matrix.browsers }}
