merge-reports:
    needs: cypress-run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Raw Reports
        uses: actions/download-artifact@v4
        with:
          pattern: mochawesome-raw-reports-*
          path: cypress/reports

      - name: Create Report Directory
        run: mkdir -p cypress/reports

      - name: Merge Mochawesome Reports
        run: npx mochawesome-merge "cypress/reports/**/*.json" > "cypress/reports/merged-reports.json"

      - name: Generate HTML Report
        run: npx marge "cypress/reports/merged-reports.json" --reportDir "cypress/reports" -f "merged-report.html"

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Merged HTML Report
          path: cypress/reports/merged-report.html
