name: Cypress Tests

on:
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chrome, firefox, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run in ${{ matrix.browsers }}
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser ${{ matrix.browsers }} --reporter-options reportDir=cypress/reports/${{ matrix.browsers }}
        env:
          # Enable screenshots on test failure
          CYPRESS_SCREENSHOT_ON_FAILURE: true
          # Enable video recording for the entire run
          CYPRESS_VIDEO: true
          # Optionally customize the video filename (will be prefixed with spec name)
          CYPRESS_VIDEO_FILENAME: ${{ matrix.browsers }}-video.mp4
          # Optionally customize the video folder
          CYPRESS_VIDEOS_FOLDER: cypress/videos/${{ matrix.browsers }}
          # Optionally customize the screenshots folder
          CYPRESS_SCREENSHOTS_FOLDER: cypress/screenshots/${{ matrix.browsers }}

      - name: Merge Mochawesome Reports
        run: npx mochawesome-merge cypress/reports/${{ matrix.browsers }}/*.json > cypress/reports/${{ matrix.browsers }}/merged-reports.json

      - name: Generate HTML Reports
        run: npx marge cypress/reports/${{ matrix.browsers }}/merged-reports.json --reportDir cypress/reports/${{ matrix.browsers }} -f "${{ matrix.browsers }}-report.html"

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: Cypress HTML Report ${{ matrix.browsers }}
          path: cypress/reports/${{ matrix.browsers }}

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always() # Keep screenshots even if tests pass
        with:
          name: Cypress Screenshots ${{ matrix.browsers }}
          path: cypress/screenshots/${{ matrix.browsers }}

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always() # Keep videos even if tests pass
        with:
          name: Cypress Videos ${{ matrix.browsers }}
          path: cypress/videos/${{ matrix.browsers }}
